apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "andrefsilveira1/k8s-go:v2"
          envFrom:
            - configMapRef:
                name: goserver-env
          # env:
          #   - name: USER-CONTEXT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: USER-CONTEXT
          #   - name: DATE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: TEMP